apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nu6m
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yaec-tenant/rhtap-demo-app/hacbs-test-project-nu6m@sha256:121ee107e1c2b20f0ef00b419c6a436072ba838fcdff87ddcd7e82cadadd4da8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
